services:
  - type: web
    name: neuralcare
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: HF_TOKEN
        scope: run
        sync: false
      - key: PYTHONUNBUFFERED
        value: true
